# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.DefinitionName)_$(Date:yyyyMMdd))

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 0
  minor: 0
  patch: $(Build.BuildID)
  buildVersion: $(major).$(minor).$(patch)

stages:
- stage: Init
  jobs:
  - job: InitJob
    displayName: JOB -> Installing dependencies (Init)
    steps:
      - script: echo Init!
      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: .\bootstrap.ps1
- stage: Build
  jobs:
  - job: BuildJob
    displayName: JOB -> Building TerminalBuddy
    steps:
    - script: echo Building!
  dependsOn: [Init]

